CLASS ycl_abapgitchallenge_week1 DEFINITION
  PUBLIC
  FINAL
  CREATE PUBLIC .

  PUBLIC SECTION.
  PROTECTED SECTION.
  PRIVATE SECTION.
ENDCLASS.



CLASS ycl_abapgitchallenge_week1 IMPLEMENTATION.
ENDCLASS.
